name: Run omnibus bootstrap test

on:
  workflow_dispatch:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test:
    name: Run omnibus bootstrap test
    runs-on: ubuntu-latest
    steps:

      - name: cd
        run: cd /mnt
        
      - name: df
        run: df -h

      - name: find
        run: find /mnt -maxdepth 2 -exec du -shx {} \;

      - name: Checkout code
        uses: actions/checkout@v4

